#!/usr/bin/env python
# -*- coding: utf-8 -*-

from bs4 import BeautifulSoup
import urllib
import sys
import re
import redis

def process(string):
	string = string.replace('\n', ' ')
	string = re.sub(" +", " ", string)
	return string.lower()

def getRedisCommand():
	commands = dict()
	commands.setdefault('append', 2)
	commands.setdefault('auth', 1)
	commands.setdefault('bgrewriteaof', 0)
	commands.setdefault('bgsave', 0)
	commands.setdefault('bitcount', -1)
	commands.setdefault('bitop', -1)
	commands.setdefault('blpop', -1)
	commands.setdefault('brpop', -1)
	commands.setdefault('brpoplpush', 3)
	commands.setdefault('client_kill', 1)
	commands.setdefault('client_list', 0)
	commands.setdefault('client_getname', 0)
	commands.setdefault('client_setname', 1)
	commands.setdefault('config_get', 1)
	commands.setdefault('config_set', 2)
	commands.setdefault('config_resetstat', 0)
	commands.setdefault('dbsize', 0)
	commands.setdefault('debug_object', 1)
	commands.setdefault('debug_segfault', 0)
	commands.setdefault('decr', 1)
	commands.setdefault('decrby', 2)
	commands.setdefault('del', -1)
	commands.setdefault('discard', 0)
	commands.setdefault('dump', 1)
	commands.setdefault('echo', 1)
	commands.setdefault('eval', -1)
	commands.setdefault('evalsha', -1)
	commands.setdefault('exec', 0)
	commands.setdefault('exists', 1)
	commands.setdefault('expire', 2)
	commands.setdefault('expireat', 2)
	commands.setdefault('flushall', 0)
	commands.setdefault('flushdb', 0)
	commands.setdefault('get', 1)
	commands.setdefault('getbit', 2)
	commands.setdefault('getrange', 3)
	commands.setdefault('getset', 2)
	commands.setdefault('hdel', -1)
	commands.setdefault('hexists', 2)
	commands.setdefault('hget', 2)
	commands.setdefault('hgetall', 1)
	commands.setdefault('hincrby', 3)
	commands.setdefault('hincrbyfloat', 3)
	commands.setdefault('hkeys', 1)
	commands.setdefault('hlen', 1)
	commands.setdefault('hmget', -1)
	commands.setdefault('hmset', -1)
	commands.setdefault('hset', 3)
	commands.setdefault('hsetnx', 3)
	commands.setdefault('hvals', 1)
	commands.setdefault('incr', 1)
	commands.setdefault('incrby', 2)
	commands.setdefault('incrbyfloat', 2)
	commands.setdefault('info', -1)
	commands.setdefault('keys', 1)
	commands.setdefault('lastsave', 0)
	commands.setdefault('lindex', 2)
	commands.setdefault('linsert', 4)
	commands.setdefault('llen', 1)
	commands.setdefault('lpop', 1)
	commands.setdefault('lpush', -1)
	commands.setdefault('lpushx', 2)
	commands.setdefault('lrange', 3)
	commands.setdefault('lrem', 3)
	commands.setdefault('lset', 3)
	commands.setdefault('ltrim', 3)
	commands.setdefault('mget', -1)
	commands.setdefault('migrate', 5)
	commands.setdefault('monitor', 0)
	commands.setdefault('move', 2)
	commands.setdefault('mset', -1)
	commands.setdefault('msetnx', -1)
	commands.setdefault('multi', 0)
	commands.setdefault('object', -1)
	commands.setdefault('persist', 1)
	commands.setdefault('pexpire', 2)
	commands.setdefault('pexpireat', 2)
	commands.setdefault('ping', 0)
	commands.setdefault('psetex', 3)
	commands.setdefault('psubscribe', -1)
	commands.setdefault('pttl', 1)
	commands.setdefault('publish', 2)
	commands.setdefault('punsubscribe', -1)
	commands.setdefault('quit', 0)
	commands.setdefault('randomkey', 0)
	commands.setdefault('rename', 2)
	commands.setdefault('renamenx', 2)
	commands.setdefault('restore', 3)
	commands.setdefault('rpop', 1)
	commands.setdefault('rpoplpush', 2)
	commands.setdefault('rpush', -1)
	commands.setdefault('rpushx', 2)
	commands.setdefault('sadd', -1)
	commands.setdefault('save', 0)
	commands.setdefault('scard', 1)
	commands.setdefault('script_exists', -1)
	commands.setdefault('script_flush', 0)
	commands.setdefault('script_kill', 0)
	commands.setdefault('script_load', 1)
	commands.setdefault('sdiff', -1)
	commands.setdefault('sdiffstore', -1)
	# commands.setdefault('select', 1) redis-py
	commands.setdefault('set', -1)
	commands.setdefault('setbit', 3)
	commands.setdefault('setex', 3)
	commands.setdefault('setnx', 2)
	commands.setdefault('setrange', 3)
	commands.setdefault('shutdown', -1)
	commands.setdefault('sinter', -1)
	commands.setdefault('sinterstore', -1)
	commands.setdefault('sismember', 2)
	commands.setdefault('slaveof', 2)
	commands.setdefault('slowlog', -1)
	commands.setdefault('smembers', 1)
	commands.setdefault('smove', 3)
	commands.setdefault('sort', -1)
	commands.setdefault('spop', 1)
	commands.setdefault('srandmember', -1)
	commands.setdefault('srem', -1)
	commands.setdefault('strlen', 1)
	commands.setdefault('subscribe', -1)
	commands.setdefault('sunion', -1)
	commands.setdefault('sunionstore', -1)
	commands.setdefault('sync', 0)
	commands.setdefault('time', 0)
	commands.setdefault('ttl', 1)
	commands.setdefault('type', 1)
	commands.setdefault('unsubscribe', -1)
	commands.setdefault('unwatch', 0)
	commands.setdefault('watch', -1)
	commands.setdefault('zadd', -1)
	commands.setdefault('zcard', 1)
	commands.setdefault('zcount', 3)
	commands.setdefault('zincrby', 3)
	commands.setdefault('zinterstore', -1)
	commands.setdefault('zrange', -1)
	commands.setdefault('zrangebyscore', -1)
	commands.setdefault('zrank', 2)
	commands.setdefault('zrem', -1)
	commands.setdefault('zremrangebyrank', 3)
	commands.setdefault('zremrangebyscore', 3)
	commands.setdefault('zrevrange', -1)
	commands.setdefault('zrevrangebyscore', -1)
	commands.setdefault('zrevrank', 2)
	commands.setdefault('zscore', 2)
	commands.setdefault('zunionstore', -1)
	return commands

if __name__ == '__main__':
	sys.stdout = open("command.list", "w")
	url = "http://redis.io/commands"

	soup = BeautifulSoup(urllib.urlopen(url).read())
	for command in soup.find_all("span", class_ = "command"):
		strings = [process(str(x)) for x in command.stripped_strings]
		command = strings[0].replace(' ', '_')

		if len(strings) == 1:
			print "commands.setdefault('%s', 0)" % command.lower()
		else:
			args = strings[1]
			print "commands.setdefault('%s', %d)" % (command.lower(), -1 if args.find('[') != -1 else len(args.split()))

	print getRedisCommand()
